// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piiiypgfzmzpymiklyem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpaWl5cGdmem16cHltaWtseWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzM5MDQsImV4cCI6MjA1NzQwOTkwNH0.0Z2vcano4xesZVVMwxxQPOb6G7DPFWDI84gb4sCRGJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);